development:
  nytimes_base_uri: "http://api.nytimes.com/svc/movies/v2/reviews/search.json?"
  nytimes_review_key: "247b93157509e7e302709ee77c987b3d:17:69904243"

test:
  nytimes_base_uri: "http://api.nytimes.com/svc/movies/v2/reviews/search.json?"
  nytimes_review_key: "247b93157509e7e302709ee77c987b3d:17:69904243"