development:
  adapter: postgresql
  database: park_bench_app-dev
  username: postgres
  password: postgres
  host: localhost

test:
  adapter: postgresql
  database: park_bench_app-test
  username: postgres
  password: postgres
  host: localhost

production:
  adapter: postgresql
  database: park_bench_app-prod
  username: postgres
  password: postgres
  host: localhost